spring:
  datasource:
    url : jdbc:mysql://localhost:3312/todo_list_db
    username : dhgo
    password : admin1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa :
    hibernate :
      ddl-auto : update
    show-sql : true


logging:
  level:
    org.hibernate.SQL: DEBUG
